-- AlterTable
ALTER TABLE "LocationDetail" ADD COLUMN     "area" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "length" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "planting_date" DROP NOT NULL,
ALTER COLUMN "planting_date" DROP DEFAULT;
