export const harvestSchema = {
  body: {
    type: "object",
    required: [
      "datetime",
      "harvestLocation",
      "pic",
      "frozenWeight",
      "wastedWeight",
      "total",
      "totalExMomoka",
    ],
    properties: {
      datetime: { type: "string" },
      harvestLocation: { type: "string" },
      pic: { type: "string" },
      packGradeA: { type: "number" },
      packGradeA15pcs: { type: "number" },
      frozenWeight: { type: "number" },
      wastedWeight: { type: "number" },
      packGradeB: { type: "number" },
      momoka3pcs: { type: "number" },
      momokaA11: { type: "number" },
      momokaA15: { type: "number" },
      momokaGradeB: { type: "number" },
      hatsuhana3pcs: { type: "number" },
      hatsuhana4pcs: { type: "number" },
      hatsuhana6pcs: { type: "number" },
      giftbox: { type: "number" },
      total: { type: "number" },
      totalExMomoka: { type: "number" },
    },
  },
};
